### PR TITLE
Fix: 24 | additional null check for initial call arguments

### PR DESCRIPTION
**Pull request by barelyhuman**
fix: #24 

Also additional test case and fix for no-deps `useEffect` since it can cause tearing on significant renders

### CODE REVIEW

**Comment by barelyhuman** [comment]
@axelson
This should fix the issue, we'd like you to check it through using the codesandbox builds above until a new release is published

**Comment by axelson** [comment]
@barelyhuman thanks for this fix! Is there a way I can run eslint in the codesandbox? I'm not seeing a console where I can run `npx eslint`

**Review by dai-shi — APPROVED** [review]
The change looks fair.

**Comment by barelyhuman** [comment]
> @barelyhuman thanks for this fix! Is there a way I can run eslint in the codesandbox? I'm not seeing a console where I can run `npx eslint`

nah, you can’t. 
though, you can use the builds generated by codesandbox

https://ci.codesandbox.io/status/pmndrs/eslint-plugin-valtio/pr/25/builds/250278

use the “local install instructions” to use this PR’s build

**Comment by axelson** [comment]
@barelyhuman Thanks for the testing instructions!

Unfortunately on my production project I'm still running into: https://github.com/pmndrs/eslint-plugin-valtio/issues/24 even when I'm using `"eslint-plugin-valtio": "https://pkg.csb.dev/pmndrs/eslint-plugin-valtio/commit/13591806/eslint-plugin-valtio"`

**Comment by barelyhuman** [comment]
is it possible for you to create a reproduction project for the same? not a sandbox, a normal repo. i can’t seem to get the same error

**Comment by barelyhuman** [comment]
> @barelyhuman Thanks for the testing instructions!
> 
> Unfortunately on my production project I'm still running into: #24 even when I'm using `"eslint-plugin-valtio": "https://pkg.csb.dev/pmndrs/eslint-plugin-valtio/commit/13591806/eslint-plugin-valtio"`

@axelson 
Make sure you re-install the `node-modules` and do that after removing any `.lock` files
and test that again. 
If not, I'd be happy to help with a simple github repo reproducing this issue :)

**Pull request merged**
