### PR TITLE
New failed test

### PR DESCRIPTION
**Pull request by nosferatu500**
Good day!

I've prepared another failing test to pass.

in this test I have the following message on line 117

`"Mutating a proxy object itself. this might not be expected as it's not reactive."`

### CODE REVIEW

**Comment by dai-shi** [comment]
We'd need to ask help for @barelyhuman .

I would be nice to have more contributors. Anyone?

**Comment by barelyhuman** [comment]
I think there was another issue that I needed to pick up, I've been packed with work so I'll pick this up in a bit

**Comment by barelyhuman** [comment]
I'm surprised this was never found out 😂

There is a tiny flaw in how an object or member is considered a valtio variable and any object in the render expression would be considered a proxy if there's a `useSnapshot` in the component

Fixing this, give me a few

**Review by dai-shi — APPROVED** [review]
Thanks guys!

**Comment by dai-shi** [comment]
@Aslemammad Can you merge and release a patch?

**Comment by Aslemammad** [comment]
Hey folks, sure, but I do not have an access right now to my main computer, if anyone needs an access, send me their npm email address. if not, I'll do that soon.

**Pull request merged**
