### PR TITLE
feat(core): support for v9 configs

### PR DESCRIPTION
**Pull request by barelyhuman**
Add v9 config support with backward compat for v8

- [x] Remove Modified API's 
- [x] Setup CI to run tests running both v8 v9 versions 
- [ ] Decide Release to be marked as breaking or not

Closes: #50

### CODE REVIEW

**Comment by barelyhuman** [comment]
@dai-shi  seems to be working, any chance you can run a local install to confirm v8 compat with one of your projects?

**Comment by dai-shi** [comment]
I don't have a good project to test. Let's see if someone can help testing.

**Comment by barelyhuman** [comment]
i tested this on a few of my projects and it seems to be working, let's get a release, I'd recommend a breaking release

**Comment by dai-shi** [comment]
v0.7.0?

**Comment by barelyhuman** [comment]
Oh right we haven't reached v1, yeah okay, v0.7.0 works. 

We'll just put it in release notes that it might be breaking

**Review by dai-shi — APPROVED** [review]
Feel free to merge this and release v0.7.0.

**Pull request merged**
