### PR TITLE
add export declaration check

### PR DESCRIPTION
**Pull request by barelyhuman**
Fix: #32 

Extend the root depth check to also handle `export` declarations

### CODE REVIEW

**Comment by barelyhuman** [comment]
@nosferatu500
You can use 
https://ci.codesandbox.io/status/pmndrs/eslint-plugin-valtio/pr/33/builds/279714

to install this PR's version of the rule and confirm if it works for you

**Comment by nosferatu500** [comment]
@barelyhuman 

Thanks! Now it's working as expected.

**Review by dai-shi — APPROVED** [review]
Looks okay. Should we release this?

**Comment by barelyhuman** [comment]
Can we wait for like 2 days? @dai-shi , i have to check if forwardRefs and useMemo also fails

**Comment by barelyhuman** [comment]
Good to go, @dai-shi

**Comment by dai-shi** [comment]
@Aslemammad Can you merge and release this?

**Pull request merged**
